# Generated by Django 6.0.6 on 2026-06-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
