# Generated by Django 6.0.6 on 2026-06-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicacao_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='publicacoes/'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
