# Generated by Django 6.0.6 on 2026-06-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicacao_imagem_publicacao_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='visualizacoes',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
